// src/pages/NotFound.jsx
import React from 'react';
import { Link } from 'react-router-dom';

export default function NotFound() {
  return (
    <div style={{ textAlign: 'center', marginTop: '80px' }}>
      <h1>404</h1>
      <p>Halaman yang Anda cari tidak ditemukan.</p>
      <Link to="/dashboard" style={{ color: '#2563eb' }}>Kembali ke Dashboard</Link>
    </div>
  );
}

// src/pages/NotFound.vue
<template>
  <div class="not-found-container">
    <h1>404</h1>
    <p>Halaman yang Anda cari tidak ditemukan.</p>
    <router-link to="/dashboard" class="btn-home">Kembali ke Dashboard</router-link>
  </div>
</template>

<style scoped>
.not-found-container { text-align: center; margin-top: 80px; }
.btn-home { color: #2563eb; text-decoration: underline; }
</style>
