// src/pages/UsersManagement.jsx
import React, { useEffect, useState } from 'react';
import { adminApi } from '../services/api';

export default function UsersManagement() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    adminApi.get('/api/admin/users')
      .then((res) => setUsers(res.data.users || res.data || []))
      .catch((err) => console.error(err));
  }, []);

  return (
    <div style={{ padding: '24px' }}>
      <h2>Manajemen Pengguna System (Admin Only)</h2>
      <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '16px' }}>
        <thead>
          <tr style={{ backgroundColor: '#f1f5f9', textAlign: 'left' }}>
            <th style={{ padding: '12px' }}>Email</th>
            <th style={{ padding: '12px' }}>Role</th>
            <th style={{ padding: '12px' }}>Status</th>
          </tr>
        </thead>
        <tbody>
          {users.map((u) => (
            <tr key={u._id} style={{ borderBottom: '1px solid #e2e8f0' }}>
              <td style={{ padding: '12px' }}>{u.email}</td>
              <td style={{ padding: '12px' }}>{u.role}</td>
              <td style={{ padding: '12px' }}>{u.status || 'ACTIVE'}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// src/pages/UsersManagement.vue
<template>
  <div class="page-container">
    <h2>Manajemen Pengguna (Admin Only)</h2>
    
    <table class="data-table">
      <thead>
        <tr>
          <th>Email</th>
          <th>Role</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="u in users" :key="u._id">
          <td>{{ u.email }}</td>
          <td>{{ u.role }}</td>
          <td>{{ u.status || 'ACTIVE' }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { adminApi } from '../services/api';

const users = ref([]);

onMounted(async () => {
  try {
    const res = await adminApi.get('/api/admin/users');
    users.value = res.data.users || res.data || [];
  } catch (err) {
    console.error('Failed to fetch users:', err);
  }
});
</script>

<style scoped>
.page-container { padding: 24px; }
.data-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
.data-table th, .data-table td { padding: 12px; border-bottom: 1px solid #e2e8f0; text-align: left; }
.data-table th { background-color: #f1f5f9; }
</style>
